### ISSUE TITLE
Offsets

### ISSUE THREAD

**Issue by gravityyusuf** [ac-1337/Alaa-8ball-pool-source-exposed#12]
Yo man I know the offsets are not updated in this one but do you have any idea if you can update the offsets ? There are 4 offsets in there I founded 2 but cant find other 2, Also do we have to update the gamemoduleAOB which is in memory file ?
Add me on discord if you feel so : Gravity#9618

**Comment by ac-1337** [comment]
we dont offer support sorry bro
