### ISSUE TITLE
Im having a issue and im getting these errors

### ISSUE THREAD

**Issue by Jakeymakey2** [ac-1337/Alaa-8ball-pool-source-exposed#15]
![image](https://user-images.githubusercontent.com/100032954/173711532-af10e25e-8acc-4692-8032-828ae2c4ab7b.png)
![image](https://user-images.githubusercontent.com/100032954/173711562-81f5d28c-9a02-4ae3-8b6c-a257906e039b.png)
![image](https://user-images.githubusercontent.com/100032954/173713917-493460ca-7108-4e90-9414-f2e8575e97ac.png)

**Comment by Jakeymakey2** [comment]
![image](https://user-images.githubusercontent.com/100032954/173714638-a2368c87-3410-4195-abe8-28b9f4fae85d.png)

**Comment by Jakeymakey2** [comment]
![image](https://user-images.githubusercontent.com/100032954/173714713-5444233a-cf1b-40ae-9f7a-e4009a231fc6.png)

**Comment by ac-1337** [comment]
Release x64, CTRL+B
