### ISSUE TITLE
I fixed the issue but 

### ISSUE THREAD

**Issue by Jakeymakey2** [ac-1337/Alaa-8ball-pool-source-exposed#17]
I fixed the issue but when i turn on anything in the menu nothing happens, I'm on version 5.7.1 of pool

**Comment by 24matan** [comment]
can you post offsets for 5.7.1

**Comment by Jakeymakey2** [comment]
> can you post offsets for 5.7.1

#pragma once

#include <basetsd.h>

namespace gOffsets
{
	constexpr SIZE_T SharedUserInfo = 0x34F6C04UL;
	constexpr SIZE_T SharedGameManager = 0x3434668UL;
	constexpr SIZE_T CUE_PROPERTIES_MAX_POWER = 0x34B5F18UL;
	constexpr SIZE_T CUE_PROPERTIES_SPIN = 0x34B5F20UL;
} 



this is the offsets he had put into it I'm not sure about any others

**Comment by claudiuko** [comment]
can you post the offsets for 5.8.0?

**Comment by ac-1337** [comment]
Hi i am gonna dump the offsets when i am home

**Comment by MrGlonks** [comment]
> > can you post offsets for 5.7.1
> 
> #pragma once
> 
> #include <basetsd.h>
> 
> namespace gOffsets { constexpr SIZE_T SharedUserInfo = 0x34F6C04UL; constexpr SIZE_T SharedGameManager = 0x3434668UL; constexpr SIZE_T CUE_PROPERTIES_MAX_POWER = 0x34B5F18UL; constexpr SIZE_T CUE_PROPERTIES_SPIN = 0x34B5F20UL; }
> 
> this is the offsets he had put into it I'm not sure about any others

how do you dump offsets?

**Comment by Mikhail-jax** [comment]
> > namespace gOffsets
> > {
> > constexpr SIZE_T SharedUserInfo = 0x34F6C04UL;
> > constexpr SIZE_T SharedGameManager = 0x3434668UL;
> > constexpr SIZE_T CUE_PROPERTIES_MAX_POWER = 0x34B5F18UL;
> > constexpr SIZE_T CUE_PROPERTIES_SPIN = 0x34B5F20UL;
> > }
> 
> this is old offsest for 5.7.1 version 
> 

How do find them

**Comment by 1Dragos12** [comment]
> How did you find them
open the Offsets.cpp in notepad ++, sublime text or visual studio l

**Comment by Mikhail-jax** [comment]
> > How did you find them
> open the Offsets.cpp in notepad ++, sublime text or visual studio l
> 
> 
> 

How can we dump the new update offsets or this source code is none useful

**Comment by Mikhail-jax** [comment]
> > > How did you find them
> > open the Offsets.cpp in notepad ++, sublime text or visual studio l
> > 
> > 
> > 
> 
> How can we dump the new update offsets or this source code is none useful any cuz the original owner Started selling the Cheto

**Comment by DrHeisen** [comment]
they don't even make a free version

**Comment by DrHeisen** [comment]
they don't even make a free version

**Comment by Jakeymakey2** [comment]
> Hi i am gonna dump the offsets when i am home

.

**Comment by DrHeisen** [comment]
Thank

**Comment by ac-1337** [comment]
This was the most active thread, but ive fixed everything. Have a wonderfull day.
