### ISSUE TITLE
Build errors.

### ISSUE THREAD

**Issue by claudiuko** [ac-1337/Alaa-8ball-pool-source-exposed#18]
![image](https://user-images.githubusercontent.com/73667404/174434730-d8a2ddae-dac3-46b3-afd7-e19a73456501.png)

**Comment by Mikhail-jax** [comment]
What language used her

**Comment by 1Dragos12** [comment]
> ![image](https://user-images.githubusercontent.com/73667404/174434730-d8a2ddae-dac3-46b3-afd7-e19a73456501.png)

Use Visual studio 2022 for compiling and install Desktop Development with c++ and Universal Windows Platform development

**Comment by Frazix12** [comment]
> > ![image](https://github.com/assets/73667404/d8a2ddae-dac3-46b3-afd7-e19a73456501)
> 
> Use Visual studio 2022 for compiling and install Desktop Development with c++ and Universal Windows Platform development

doesn't work

**Comment by ac-1337** [comment]
Use visual studio 2019, Relase x64
