### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by GamerulEDY** [ac-1337/Alaa-8ball-pool-source-exposed#7]
so when i do ctrl+b on release x64 is not working i get this errors any fix? https://prnt.sc/Ug9X6lQcQq58

**Comment by ac-1337** [comment]
Give me your discord

**Comment by GamerulEDY** [comment]
edy#0054

**Comment by samuelsiv** [comment]
Compile as x86 Release

**Comment by ac-1337** [comment]
Added, closed.
